### ISSUE TITLE
Add ability to "tell" multiple users with tell command

### ISSUE THREAD

**Issue by patcon** [gratipay/roobot#36]
https://botbot.me/freenode/gittip/msg/12698505/

Just makes sense :)
### Todo
- [ ] extract [`tell.coffee`](https://github.com/pfenwick) in npm package as per https://github.com/github/hubot-scripts/issues/1113
- [ ] deprecate community `tell.coffee` script
- [ ] add ability to run `hubot tell whit537,bruceadams a thing i want to tell them`

cc: @pjf
